In [31]:
import pandas as pd

import numpy as np
import torch

In [32]:
import torch.nn

In [33]:
data1=pd.read_csv("bdata1.csv")

In [34]:
data1.dtypes

0    int64
1    int64
2    int64
3    int64
4    int64
5    int64
6    int64
7    int64
8    int64
9    int64
dtype: object

In [35]:
data2=data1.to_numpy()

In [36]:
data2.dtype

dtype('int64')

In [37]:
data3= torch.tensor(data2, dtype=torch.float32)


In [38]:
data3[0]

tensor([0., 1., 1., 1., 1., 1., 0., 1., 0., 0.])

In [39]:
model1=torch.nn.Sequential(torch.nn.Linear(10,2, bias=False), torch.nn.Linear(2,10, bias=False))

In [40]:
model1

Sequential(
  (0): Linear(in_features=10, out_features=2, bias=False)
  (1): Linear(in_features=2, out_features=10, bias=False)
)

In [41]:
optimizer= torch.optim.SGD(model1.parameters(), 1e-2)

In [42]:
def training_loop(n_epochs, optimizer, model, loss_fun, input, output): 
    for epoch in range(1, n_epochs + 1):
        p = model(input)
        loss = loss_fun(p, output) 
       # print('loss',loss)
        optimizer.zero_grad() 
        loss.backward() 
        optimizer.step()
        if epoch == 1 or epoch % 1000 == 0:
            print('Epoch {}, Loss {}'.format(epoch, float(loss)))

In [43]:
training_loop( n_epochs = 5000,
optimizer = optimizer, 
model = model1,
loss_fun = torch.nn.MSELoss(), 
input = data3,
output = data3)


Epoch 1, Loss 0.5004283785820007
Epoch 1000, Loss 0.19798381626605988
Epoch 2000, Loss 0.11529742926359177
Epoch 3000, Loss 0.09788785129785538
Epoch 4000, Loss 0.09466427564620972
Epoch 5000, Loss 0.09371545910835266


In [82]:
print(list(model1.parameters()))

[Parameter containing:
tensor([[ 0.3414,  0.2558,  0.5017,  0.2440,  0.4987,  0.1608, -0.2878,  0.1132,
          0.0691,  0.0937],
        [ 0.1014,  0.0949, -0.0166, -0.0361, -0.0046,  0.5716,  0.4333,  0.1460,
          0.3518,  0.3878]], requires_grad=True), Parameter containing:
tensor([[ 0.4809,  0.0212],
        [ 0.4641, -0.0563],
        [ 0.5070, -0.1299],
        [ 0.5082, -0.1311],
        [ 0.5819,  0.1034],
        [ 0.0531,  0.5391],
        [-0.1569,  0.6052],
        [ 0.0533,  0.5389],
        [ 0.0177,  0.4617],
        [-0.1071,  0.4831]], requires_grad=True)]


Can you use the encoder matrix to compute the code for each of the ten rows as input?
Ans: Yes. we can compute the code

In [85]:
model1[0].parameters()

Model_par = np.array([( 0.3414,  0.2558,  0.5017,  0.2440,  0.4987,  0.1608, -0.2878,  0.1132,
          0.0691,  0.0937),
        (0.1014,  0.0949, -0.0166, -0.0361, -0.0046,  0.5716,  0.4333,  0.1460,
          0.3518,  0.3878)])
Model_par.shape

(2, 10)

In [86]:
New_data=data3.numpy()
New_data.shape
output = np.matmul(Model_par, New_data)

output


array([[1.661 , 1.5858, 1.5976, 1.5976, 2.0961, 0.6407, 0.149 , 0.6407,
        0.5786, 0.0358],
       [0.6092, 0.0441, 0.1751, 0.1751, 1.0984, 1.568 , 1.8905, 1.568 ,
        1.5341, 1.7445]])

 Which of the two nodes in the code reveals the two types of inputs?
    Ans: Linear(in_features=10, out_features=2, bias=False). 10*2 node reveals types of inputs. Hidden 2 neurons.